MAX_SMS_GOLD = 250
MAW_SMS_ARGENT = 25
MAX_SMS_NORMAL = 5

MAX_ARCHIVES_GOLD = 500
MAX_ARCHIVES_ARGENT = 50
MAX_ARCHIVES_NORMAL = 5

MAX_TRACKERS_GOLD = 25
MAX_TRACKERS_ARGENT = 5
MAX_TRACKERS_NORMAL = 1
